import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/module/lib/components/SideBar";
import TopNav from "@/module/lib/components/TopNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Todo System [Frontend Developer Assignment]",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="w-full h-screen overflow-y-hidden"
          style={{
            display: "grid",
            gridTemplateColumns: "auto 1fr",
          }}
        >
          <SideBar />
          <div className="h-[100vh]">
            <TopNav />
            <div className="h-full overflow-y-scroll no-scrollbar">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
